version: "3.9"
services:


 
 
  ProduitPrimaire:
    container_name: produitprimaire
    build: .\produitp
    ports:
      - "8087:8087"   
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/ProduitsPrimaires?createDatabaseIfNotExist=true&userSSL=false&max_allowed_packet=15728640
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/     
      
    image: produitp
    restart: unless-stopped
    depends_on:
      - Eureka
      - db-mysql
    
 
  Eureka:
    container_name: eureka
    build: .\Eureka
    hostname: serviceregistry
    ports:
      - "8761:8761"   
    image: eureka    
    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/
    
  
  db-mysql:
      image: "mysql:8.0"
      container_name: db-mysql 
      environment:
        - MYSQL_ROOT_PASSWORD=root  #indisponsable pour la conteneurisation
        #- MYSQL_DATABASE=job
      ports:
        - "3307:3306"
      restart: unless-stopped
      
      
  api-gateway:
    build: .\APIGateway2
    container_name: apigateway2
    image: apigateway2
    ports:
      - "8095:8095"  # Port mapping pour l'API Gateway
    environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/     
    depends_on:
      - Eureka
      - ProduitPrimaire